Throw an error if dashes are used
FontoXML/fontoxml-localization-tools pull request #4
Opened 2018-08-27 13:34 UTC by Martinn1996

Since version 2 of MessageFormat, dashes, "-", can no longer be used. 
So if we detect a dash, we will throw an error.

2018-08-29 07:00 UTC, bwrrp requested changes
Looks good. Instead of translating the string to underscores, let's just throw directly from the parser when dashes are matched in the wrong context, and catch + re-throw in Message.js with an error that includes the full message.

2018-08-31 14:46 UTC, DrRataplan approved these changes
Looks great! If you can edit the parser to just throw instead of returning a '_', that would be awesome.

2018-09-05 10:06 UTC, DrRataplan commented on src/parser.pegjs
> +id = x:('-' { throw new Error("Dashes are now allowed (-)")} / $[^\u0009-\u000d \u0085\u200e\u200f\u2028\u2029\u0021-\u002f\u003a-\u0040\u005b-\u005e\u0060\u007b-\u007e\u00a1-\u00a7\u00a9\u00ab\u00ac
are no*t*

2018-09-05 10:07 UTC, bwrrp requested changes

2018-09-05 10:07 UTC, bwrrp commented on src/Message.js
> +		parser.parse(props.original);
Let's catch and re-throw the error in both cases in order to include the full message: `Dashes are not allowed in identifiers, in message "${props.original}"`

2018-09-05 10:07 UTC, bwrrp commented on src/parser.pegjs
> +id = x:('-' { throw new Error("Dashes are now allowed (-)")} / $[^\u0009-\u000d \u0085\u200e\u200f\u2028\u2029\u0021-\u002f\u003a-\u0040\u005b-\u005e\u0060\u007b-\u007e\u00a1-\u00a7\u00a9\u00ab\u00ac
I think only this code block is still necessary, and the rest can be removed?

2018-09-05 12:39 UTC, merged